# GoWAFer 配置文件

ratelimiter:
  bancounter: 100
  banduration: 60
  fixedwindow:
    maxrequest: 3
    windowsize: 3
  leakybucket:
    capacity: 3
    leakypersecond: 1
  maxcounter: 400
  mode: 1
  slidewindow:
    maxrequest: 3
    windowsize: 3
  tokenbucket:
    maxtoken: 3
    tokenpersecond: 1
secret:
  jwtsecretkey: 123456adad
  sessionsecretkey: snadkadmsa
server:
  targetaddress: http://127.0.0.1:8080
  wafport: 80
