definitions:
  api_helper.LoginRequest:
    properties:
      captcha:
        type: string
      captchaId:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - captcha
    - captchaId
    - password
    - username
    type: object
  api_helper.Response:
    properties:
      data:
        type: object
      msg:
        type: string
      status:
        type: integer
    type: object
  config.Config:
    properties:
      rateLimiter:
        description: 限速器配置
        properties:
          banCounter:
            description: 计数器常规值，超过触发常规封禁时间
            type: integer
          banDuration:
            description: 常规封禁时间，单位秒
            type: integer
          fixedWindow:
            description: 固定窗口模式配置
            properties:
              maxRequest:
                description: 窗口内最大请求数
                type: integer
              windowSize:
                description: 窗口大小,单位秒
                type: integer
            type: object
          leakyBucket:
            description: 漏桶模式配置
            properties:
              capacity:
                description: 桶容量
                type: integer
              leakyPerSecond:
                description: 漏水速度，单位秒
                type: integer
            type: object
          maxCounter:
            description: 计数器最大值，超过该值拉入永久IP黑名单
            type: integer
          mode:
            description: 限速算法，1:令牌桶2:漏桶3:固定窗口4:滑动窗口
            type: integer
          slideWindow:
            description: 滑动窗口模式配置
            properties:
              maxRequest:
                description: 窗口内最大队列数
                type: integer
              windowSize:
                description: 窗口大小，单位秒
                type: integer
            type: object
          tokenBucket:
            description: 令牌桶模式配置
            properties:
              maxToken:
                description: 最大令牌数
                type: integer
              tokenPerSecond:
                description: 令牌生成速度，单位秒
                type: integer
            type: object
        type: object
      secret:
        properties:
          jwtSecretKey:
            type: string
          sessionSecretKey:
            type: string
        type: object
      server:
        properties:
          targetAddress:
            type: string
        type: object
    type: object
  types.AddIPRequest:
    properties:
      expiration:
        type: integer
      ip:
        type: string
      isBlack:
        type: boolean
    required:
    - ip
    type: object
  types.AddRoutingRequest:
    properties:
      isBlack:
        type: boolean
      path:
        type: string
    required:
    - path
    type: object
  types.AddSqlInjectRuleRequest:
    properties:
      rule:
        type: string
    required:
    - rule
    type: object
  types.DeleteIPRequest:
    properties:
      ip:
        type: string
      isBlack:
        type: boolean
    required:
    - ip
    type: object
  types.DeleteRoutingRequest:
    properties:
      isBlack:
        type: boolean
      path:
        type: string
    required:
    - path
    type: object
  types.DeleteSqlInjectRuleRequest:
    properties:
      rule:
        type: string
    required:
    - rule
    type: object
  types.DeleteXssDetectRuleRequest:
    properties:
      rule:
        type: string
    required:
    - rule
    type: object
  types.XssDetectRule:
    properties:
      rule:
        type: string
    type: object
info:
  contact: {}
  description: Golang编写的一款基于反向代理模式的web防火墙应用 By supercat0867
  license: {}
  title: GoWAFer
  version: v1.0
paths:
  /waf/api/v1/auth/dologin:
    post:
      consumes:
      - application/json
      description: dologin
      parameters:
      - description: 请求体
        in: body
        name: api_helper.LoginRequest
        required: true
        schema:
          $ref: '#/definitions/api_helper.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 处理登录
      tags:
      - Auth
  /waf/api/v1/auth/getCaptcha:
    get:
      consumes:
      - application/json
      description: 获取图片验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 获取图片验证码
      tags:
      - Auth
  /waf/api/v1/config:
    get:
      description: 获取配置信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 获取配置信息
      tags:
      - Config
    put:
      description: 修改配置文件并重启服务
      parameters:
      - description: 请求体
        in: body
        name: config.Config
        required: true
        schema:
          $ref: '#/definitions/config.Config'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 修改配置文件
      tags:
      - Config
  /waf/api/v1/ip:
    delete:
      consumes:
      - application/json
      description: 删除IP记录
      parameters:
      - description: 请求体
        in: body
        name: types.DeleteIPRequest
        required: true
        schema:
          $ref: '#/definitions/types.DeleteIPRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 删除IP记录
      tags:
      - IP
    get:
      description: 分页查询IP管理记录
      parameters:
      - description: 查询关键字
        in: query
        name: query
        type: string
      - description: 是否为黑名单
        in: query
        name: isBlack
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 页面大小
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 分页查询IP管理记录
      tags:
      - IP
    post:
      consumes:
      - application/json
      description: 新增IP记录
      parameters:
      - description: 请求体
        in: body
        name: types.AddIPRequest
        required: true
        schema:
          $ref: '#/definitions/types.AddIPRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 新增IP管理记录
      tags:
      - IP
  /waf/api/v1/log:
    get:
      description: 查询指定天数和小时数的日志记录
      parameters:
      - description: 查询范围天数
        in: query
        name: days
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 查询指定天数和小时数的日志记录
      tags:
      - Log（日志模块）
  /waf/api/v1/log/getBlockLog:
    get:
      description: 分页查询被拦截的流量日志
      parameters:
      - description: ip搜索
        in: query
        name: ip
        type: string
      - description: 封禁原因搜索
        in: query
        name: block_by
        type: string
      - description: HTTP方法搜索
        in: query
        name: method
        type: string
      - description: 日期排序
        in: query
        name: orderDir
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 页面大小
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 分页查询被拦截的流量日志
      tags:
      - Log（日志模块）
  /waf/api/v1/routing:
    delete:
      consumes:
      - application/json
      description: 删除路由管理记录
      parameters:
      - description: 请求体
        in: body
        name: types.DeleteRoutingRequest
        required: true
        schema:
          $ref: '#/definitions/types.DeleteRoutingRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 删除路由管理记录
      tags:
      - Routing
    get:
      description: 分页查询路由管理记录
      parameters:
      - description: 查询关键字
        in: query
        name: query
        type: string
      - description: 是否为黑名单
        in: query
        name: isBlack
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 页面大小
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 分页查询路由管理记录
      tags:
      - Routing
    post:
      consumes:
      - application/json
      description: 新增路由管理记录
      parameters:
      - description: 请求体
        in: body
        name: types.AddRoutingRequest
        required: true
        schema:
          $ref: '#/definitions/types.AddRoutingRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 新增路由管理记录
      tags:
      - Routing
  /waf/api/v1/sqlInject:
    delete:
      consumes:
      - application/json
      description: 删除sql注入防护规则
      parameters:
      - description: 请求体
        in: body
        name: types.DeleteSqlInjectRuleRequest
        required: true
        schema:
          $ref: '#/definitions/types.DeleteSqlInjectRuleRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 删除sql注入防护规则
      tags:
      - SqlInject
    get:
      description: 查询全部sql注入防护规则
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 查询全部sql注入防护规则
      tags:
      - SqlInject
    post:
      consumes:
      - application/json
      description: 新增sql注入防护规则
      parameters:
      - description: 请求体
        in: body
        name: types.AddSqlInjectRuleRequest
        required: true
        schema:
          $ref: '#/definitions/types.AddSqlInjectRuleRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 新增sql注入防护规则
      tags:
      - SqlInject
  /waf/api/v1/xssDetect:
    delete:
      consumes:
      - application/json
      description: 删除xss攻击防护规则
      parameters:
      - description: 请求体
        in: body
        name: types.DeleteXssDetectRuleRequest
        required: true
        schema:
          $ref: '#/definitions/types.DeleteXssDetectRuleRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 删除xss攻击防护规则
      tags:
      - XssDetect
    get:
      description: 查询全部xss攻击防护规则
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 查询全部xss攻击防护规则
      tags:
      - XssDetect
    post:
      consumes:
      - application/json
      description: 新增sql注入防护规则
      parameters:
      - description: 请求体
        in: body
        name: types.XssDetectRule
        required: true
        schema:
          $ref: '#/definitions/types.XssDetectRule'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_helper.Response'
      summary: 新增xss攻击防护规则
      tags:
      - XssDetect
swagger: "2.0"
