definitions:
  api_handler.Response:
    properties:
      data:
        type: object
      msg:
        type: string
      status:
        type: integer
    type: object
  controller.LoginRequest:
    properties:
      captcha:
        type: string
      captchaID:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - captcha
    - captchaID
    - password
    - username
    type: object
info:
  contact: {}
  description: Golang编写的一款基于反向代理模式的web防火墙应用 By supercat0867
  license: {}
  title: GoWAFer
  version: v0.1
paths:
  /waf/api/v1/auth/dologin:
    post:
      consumes:
      - application/json
      description: dologin
      parameters:
      - description: request body
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/controller.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_handler.Response'
      summary: 处理登录
      tags:
      - Auth
  /waf/api/v1/auth/getCaptcha:
    get:
      consumes:
      - application/json
      description: 获取图片验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_handler.Response'
      summary: 获取图片验证码
      tags:
      - Auth
swagger: "2.0"
